modLoader="javafml" #mandatory
loaderVersion="[36,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
[[mods]] #mandatory
modId="ambientadditions" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Ambient Additions" #mandatory
credits="Coda, VakyPanda, Ninni" #optional
description='''Adds more ambient wildlife to your world!'''